import { z, type ZodType } from 'zod';
import {
  ActualizarAsociadoSchema,
  ActualizarClienteSchema,
  ActualizarConductorSchema,
  ActualizarDestinoSchema,
  ActualizarDocumentoSchema,
  ActualizarTarifaSchema,
  ActualizarTransportadoraSchema,
  ActualizarUsuarioSchema,
  ActualizarVehiculoSchema,
  ActualizarViajeSchema,
  AlertaDocumentoSchema,
  AnularViajeSchema,
  AsignarConductoresSchema,
  AsignarVehiculosSchema,
  CambiarRolSchema,
  CanjearEnlaceSchema,
  ClienteSchema,
  ConfirmarSoporteSchema,
  CrearAsociadoSchema,
  CrearClienteSchema,
  CrearConductorSchema,
  CrearDestinoSchema,
  CrearDocumentoSchema,
  CrearRequerimientoSchema,
  CrearTarifaSchema,
  CrearTransportadoraSchema,
  CrearUsuarioSchema,
  CrearVehiculoSchema,
  CrearViajeSchema,
  DeclinarOfertaSchema,
  DetalleViajeSchema,
  EventoAuditoriaSchema,
  FiltroAuditSchema,
  FiltroColaSchema,
  FiltroDocumentosSchema,
  FiltroMaestrosSchema,
  FiltroNotificacionesSchema,
  FiltroOfertasSchema,
  FiltroRecaudosSchema,
  FiltroRequerimientosSchema,
  FiltroTarifasSchema,
  FiltroTrsSchema,
  FiltroViajesSchema,
  GuardarHabilitacionSchema,
  IntervencionSchema,
  LiquidarViajeSchema,
  LoginSchema,
  MeSchema,
  MesSchema,
  MiPosicionSchema,
  MotivoDeclinacionSchema,
  MotivoSchema,
  NotificacionSchema,
  OverrideColaSchema,
  ParametrosSchema,
  PatchParametrosSchema,
  PreferenciasNotificacionSchema,
  ReauthSchema,
  RegistrarPagoSchema,
  ResetColaSchema,
  RespuestaLoginSchema,
  ResumenMesSchema,
  SemaforoPlacaSchema,
  SesionSchema,
  SnapshotMesSchema,
  SolicitarSoporteSchema,
  SolicitarAccesoSchema,
  TableroSchema,
  TipoDocumentoSchema,
  TransportadoraSchema,
  UrlSubidaSchema,
  UsuarioSesionSchema,
  VerificarOtpSchema,
  VerificarTotpSchema,
  VistaAsociadoSchema,
  VistaColaSchema,
  VistaDocumentoSchema,
  VistaFichaSchema,
  VistaHabilitacionSchema,
  VistaOfertaSchema,
  VistaRequerimientoSchema,
  VistaResumenMesSchema,
  VistaTrSchema,
  VistaVehiculoRegistroSchema,
  VistaVehiculoSchema,
  VistaViajeSchema,
} from '@asotracmet/shared';

// Contrato de la API (TASK-0033): una entrada por ruta con su guard, el esquema Zod del cuerpo o
// la query (los mismos que valida el handler) y el de la respuesta (vistas compartidas con la web).
// `openapi.test.ts` comprueba que cada ruta registrada en Fastify está aquí y viceversa, y que las
// respuestas reales cumplen las vistas. `documento.ts` lo convierte en OpenAPI 3.1.

export type Metodo = 'get' | 'post' | 'patch' | 'put' | 'delete';

export interface Respuesta {
  /** Nombre del componente (`components.schemas`). */
  nombre: string;
  /** Sin esquema, se documenta como objeto libre con la descripción. */
  schema?: ZodType;
  lista?: boolean;
  status?: number;
  descripcion?: string;
}

export interface EntradaContrato {
  metodo: Metodo;
  ruta: string;
  etiqueta: string;
  resumen: string;
  /** Guard RBAC tal como lo aplica la ruta (`recurso permiso [own]`, `público`, `token`). */
  guard: string;
  publica?: boolean;
  reauth?: boolean;
  body?: ZodType;
  query?: ZodType;
  respuesta?: Respuesta;
}

/** Nombre de componente de cada esquema compartido: el del export sin el sufijo `Schema`. */
export const NOMBRES_ESQUEMAS = new Map<ZodType, string>(
  Object.entries({
    Login: LoginSchema,
    SolicitarAcceso: SolicitarAccesoSchema,
    VerificarTotp: VerificarTotpSchema,
    VerificarOtp: VerificarOtpSchema,
    CanjearEnlace: CanjearEnlaceSchema,
    Reauth: ReauthSchema,
    CrearRequerimiento: CrearRequerimientoSchema,
    FiltroRequerimientos: FiltroRequerimientosSchema,
    DeclinarOferta: DeclinarOfertaSchema,
    Motivo: MotivoSchema,
    FiltroOfertas: FiltroOfertasSchema,
    FiltroTrs: FiltroTrsSchema,
    FiltroCola: FiltroColaSchema,
    OverrideCola: OverrideColaSchema,
    ResetCola: ResetColaSchema,
    CrearUsuario: CrearUsuarioSchema,
    ActualizarUsuario: ActualizarUsuarioSchema,
    CambiarRol: CambiarRolSchema,
    AsignarVehiculos: AsignarVehiculosSchema,
    FiltroAudit: FiltroAuditSchema,
    PatchParametros: PatchParametrosSchema,
    CrearAsociado: CrearAsociadoSchema,
    ActualizarAsociado: ActualizarAsociadoSchema,
    CrearVehiculo: CrearVehiculoSchema,
    ActualizarVehiculo: ActualizarVehiculoSchema,
    CrearConductor: CrearConductorSchema,
    ActualizarConductor: ActualizarConductorSchema,
    AsignarConductores: AsignarConductoresSchema,
    CrearCliente: CrearClienteSchema,
    ActualizarCliente: ActualizarClienteSchema,
    CrearDestino: CrearDestinoSchema,
    ActualizarDestino: ActualizarDestinoSchema,
    CrearTransportadora: CrearTransportadoraSchema,
    ActualizarTransportadora: ActualizarTransportadoraSchema,
    CrearTarifa: CrearTarifaSchema,
    ActualizarTarifa: ActualizarTarifaSchema,
    FiltroTarifas: FiltroTarifasSchema,
    CrearDocumento: CrearDocumentoSchema,
    ActualizarDocumento: ActualizarDocumentoSchema,
    FiltroDocumentos: FiltroDocumentosSchema,
    GuardarHabilitacion: GuardarHabilitacionSchema,
    FiltroMaestros: FiltroMaestrosSchema,
    CrearViaje: CrearViajeSchema,
    ActualizarViaje: ActualizarViajeSchema,
    LiquidarViaje: LiquidarViajeSchema,
    AnularViaje: AnularViajeSchema,
    RegistrarPago: RegistrarPagoSchema,
    FiltroViajes: FiltroViajesSchema,
    FiltroRecaudos: FiltroRecaudosSchema,
    ResumenMes: ResumenMesSchema,
    PreferenciasNotificacion: PreferenciasNotificacionSchema,
    FiltroNotificaciones: FiltroNotificacionesSchema,
    SolicitarSoporte: SolicitarSoporteSchema,
    ConfirmarSoporte: ConfirmarSoporteSchema,
  }).map(([nombre, schema]) => [schema, nombre]),
);

const Ok = z.object({ ok: z.literal(true) });
const Salud = z.object({ ok: z.boolean() });
const Dias = z.object({ dias: z.coerce.number().int().min(1).max(365).optional() });
const Mes = z.object({ mes: MesSchema });
const MesOpcional = z.object({ mes: MesSchema.optional() });
const MesCuerpo = z.object({ mes: MesSchema.optional() });
const Usuario = { nombre: 'Usuario', schema: UsuarioSesionSchema };
/** Override y reset devuelven la cola sin filtro de cliente ni cabeza elegible. */
const ColaIntervenida = VistaColaSchema.pick({ claseCola: true, total: true, posiciones: true });
const lista = (nombre: string, schema: ZodType): Respuesta => ({ nombre, schema, lista: true });
const una = (nombre: string, schema: ZodType, status?: number): Respuesta => ({
  nombre,
  schema,
  ...(status === undefined ? {} : { status }),
});
const libre = (nombre: string, descripcion: string, lista = false): Respuesta => ({
  nombre,
  descripcion,
  lista,
});

export const CONTRATO: readonly EntradaContrato[] = [
  // --- Salud y contrato ------------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/healthz',
    etiqueta: 'Salud',
    resumen: 'Proceso vivo',
    guard: 'público',
    publica: true,
    respuesta: una('Salud', Salud),
  },
  {
    metodo: 'get',
    ruta: '/readyz',
    etiqueta: 'Salud',
    resumen: 'Base de datos y Redis responden (503 si algo falla)',
    guard: 'público',
    publica: true,
    respuesta: libre('Readiness', '`{ ok, almacen, db: { ok, ms }, redis }`'),
  },
  {
    metodo: 'get',
    ruta: '/metrics',
    etiqueta: 'Salud',
    resumen: 'Métricas Prometheus (texto), sin PII',
    guard: 'público (METRICS_TOKEN)',
    publica: true,
    respuesta: libre('Metricas', 'text/plain en formato Prometheus'),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/openapi.json',
    etiqueta: 'Salud',
    resumen: 'Este contrato (OpenAPI 3.1)',
    guard: 'público',
    publica: true,
    respuesta: libre('OpenApi', 'Documento OpenAPI 3.1'),
  },

  // --- Acceso (spec §3.3, §8.1) ---------------------------------------------------------------------
  {
    metodo: 'post',
    ruta: '/api/v1/auth/login',
    etiqueta: 'Acceso',
    resumen: 'Contraseña → reto TOTP (o enrolamiento); sin contraseña → código o enlace por correo',
    guard: 'público, rate limit',
    publica: true,
    body: LoginSchema,
    respuesta: una('RespuestaLogin', RespuestaLoginSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/auth/2fa/verify',
    etiqueta: 'Acceso',
    resumen: 'Segundo factor: reto + código TOTP → sesión',
    guard: 'público, rate limit',
    publica: true,
    body: VerificarTotpSchema,
    respuesta: una('Sesion', SesionSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/auth/otp/verify',
    etiqueta: 'Acceso',
    resumen: 'Código por correo → sesión (roles internos)',
    guard: 'público, rate limit',
    publica: true,
    body: VerificarOtpSchema,
    respuesta: una('Sesion', SesionSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/auth/magic-link',
    etiqueta: 'Acceso',
    resumen: 'Pedir enlace de acceso (member)',
    guard: 'público, rate limit',
    publica: true,
    body: SolicitarAccesoSchema,
    respuesta: una('Ok', Ok),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/auth/magic-link/canjear',
    etiqueta: 'Acceso',
    resumen: 'Canjear el enlace (un solo uso) → sesión',
    guard: 'público, rate limit',
    publica: true,
    body: CanjearEnlaceSchema,
    respuesta: una('Sesion', SesionSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/auth/logout',
    etiqueta: 'Acceso',
    resumen: 'Revoca la sesión',
    guard: 'token',
    respuesta: una('Ok', Ok),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/auth/reauth',
    etiqueta: 'Acceso',
    resumen: 'Re-autenticación con contraseña o código para acciones sensibles',
    guard: 'token, rate limit',
    body: ReauthSchema,
    respuesta: una('Reauth', z.object({ reauthHasta: z.string() })),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/me',
    etiqueta: 'Acceso',
    resumen: 'Usuario de la sesión',
    guard: 'token',
    respuesta: una('Me', MeSchema),
  },

  // --- Catálogos y parámetros ---------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/clientes',
    etiqueta: 'Catálogos',
    resumen: 'Clientes',
    guard: 'catalogos R',
    respuesta: lista('Cliente', ClienteSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/destinos',
    etiqueta: 'Catálogos',
    resumen: 'Destinos',
    guard: 'catalogos R',
    respuesta: libre('Destino', '`{ id, nombre, ... }`', true),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/motivos-declinacion',
    etiqueta: 'Catálogos',
    resumen: 'Motivos de declinación activos',
    guard: 'catalogos R',
    respuesta: lista('MotivoDeclinacion', MotivoDeclinacionSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/vehiculos',
    etiqueta: 'Catálogos',
    resumen: 'Vehículos con habilitaciones (member: solo los suyos; viewer enmascarado)',
    guard: 'vehiculos R (own)',
    respuesta: lista('VistaVehiculo', VistaVehiculoSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/parametros',
    etiqueta: 'Catálogos',
    resumen: 'Parámetros de operación',
    guard: 'parametros R',
    respuesta: una('Parametros', ParametrosSchema),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/parametros',
    etiqueta: 'Catálogos',
    resumen: 'Cambiar parámetros (auditado con antes y después)',
    guard: 'parametros U',
    body: PatchParametrosSchema,
    respuesta: una('Parametros', ParametrosSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/audit',
    etiqueta: 'Catálogos',
    resumen: 'Auditoría append-only',
    guard: 'audit_log R (por módulo)',
    query: FiltroAuditSchema,
    respuesta: lista('EventoAuditoria', EventoAuditoriaSchema),
  },

  // --- Maestros (spec §8.3) ------------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/asociados',
    etiqueta: 'Maestros',
    resumen: 'Asociados',
    guard: 'asociados R (own)',
    query: FiltroMaestrosSchema,
    respuesta: lista('VistaAsociado', VistaAsociadoSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/asociados/:id',
    etiqueta: 'Maestros',
    resumen: 'Asociado',
    guard: 'asociados R (own)',
    respuesta: una('VistaAsociado', VistaAsociadoSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/asociados',
    etiqueta: 'Maestros',
    resumen: 'Crear asociado (cuenta bancaria cifrada, nunca sale)',
    guard: 'asociados C',
    body: CrearAsociadoSchema,
    respuesta: una('VistaAsociado', VistaAsociadoSchema, 201),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/asociados/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar asociado',
    guard: 'asociados U',
    body: ActualizarAsociadoSchema,
    respuesta: una('VistaAsociado', VistaAsociadoSchema),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/asociados/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica',
    guard: 'asociados D',
    respuesta: una('VistaAsociado', VistaAsociadoSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/vehiculos',
    etiqueta: 'Maestros',
    resumen: 'Alta de placa (entra al final de su cola)',
    guard: 'vehiculos C',
    body: CrearVehiculoSchema,
    respuesta: una('VistaVehiculoRegistro', VistaVehiculoRegistroSchema, 201),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/vehiculos/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar placa (estado o clase con motivo)',
    guard: 'vehiculos U',
    body: ActualizarVehiculoSchema,
    respuesta: una('VistaVehiculoRegistro', VistaVehiculoRegistroSchema),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/vehiculos/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica (conserva la ficha; nunca DELETE físico)',
    guard: 'vehiculos D',
    respuesta: una('VistaVehiculoRegistro', VistaVehiculoRegistroSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/vehiculos/semaforo',
    etiqueta: 'Maestros',
    resumen: 'Semáforo documental por placa',
    guard: 'vehiculos R (own)',
    respuesta: lista('SemaforoPlaca', SemaforoPlacaSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/vehiculos/:id/ficha',
    etiqueta: 'Maestros',
    resumen: 'Ficha: vehículo, asociado, conductores, documentos, habilitaciones y posición',
    guard: 'vehiculos R (own)',
    respuesta: una('VistaFicha', VistaFichaSchema),
  },
  {
    metodo: 'put',
    ruta: '/api/v1/vehiculos/:id/habilitaciones/:clienteId',
    etiqueta: 'Maestros',
    resumen: 'Habilitar o bloquear la placa para un cliente',
    guard: 'habilitaciones U',
    body: GuardarHabilitacionSchema,
    respuesta: una('VistaHabilitacion', VistaHabilitacionSchema),
  },
  {
    metodo: 'put',
    ruta: '/api/v1/vehiculos/:id/conductores',
    etiqueta: 'Maestros',
    resumen: 'Asignar conductores (uno principal)',
    guard: 'conductores U',
    body: AsignarConductoresSchema,
    respuesta: libre('Conductores', 'Conductores asignados', true),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/conductores',
    etiqueta: 'Maestros',
    resumen: 'Conductores',
    guard: 'conductores R (own)',
    query: FiltroMaestrosSchema,
    respuesta: libre('Conductor', 'Conductor (viewer enmascarado)', true),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/conductores/:id',
    etiqueta: 'Maestros',
    resumen: 'Conductor',
    guard: 'conductores R',
    respuesta: libre('Conductor', 'Conductor'),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/conductores',
    etiqueta: 'Maestros',
    resumen: 'Crear conductor',
    guard: 'conductores C',
    body: CrearConductorSchema,
    respuesta: libre('Conductor', 'Conductor creado (201)'),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/conductores/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar conductor',
    guard: 'conductores U',
    body: ActualizarConductorSchema,
    respuesta: libre('Conductor', 'Conductor'),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/conductores/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica',
    guard: 'conductores D',
    respuesta: libre('Conductor', 'Conductor'),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/clientes',
    etiqueta: 'Maestros',
    resumen: 'Crear cliente',
    guard: 'catalogos C',
    body: CrearClienteSchema,
    respuesta: una('Cliente', ClienteSchema, 201),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/clientes/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar cliente',
    guard: 'catalogos U',
    body: ActualizarClienteSchema,
    respuesta: una('Cliente', ClienteSchema),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/clientes/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica (CATALOGO_EN_USO si tiene requerimientos)',
    guard: 'catalogos D',
    respuesta: una('Cliente', ClienteSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/destinos',
    etiqueta: 'Maestros',
    resumen: 'Crear destino',
    guard: 'catalogos C',
    body: CrearDestinoSchema,
    respuesta: libre('Destino', 'Destino creado (201)'),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/destinos/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar destino',
    guard: 'catalogos U',
    body: ActualizarDestinoSchema,
    respuesta: libre('Destino', 'Destino'),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/destinos/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica',
    guard: 'catalogos D',
    respuesta: libre('Destino', 'Destino'),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/transportadoras',
    etiqueta: 'Maestros',
    resumen: 'Transportadoras',
    guard: 'catalogos R',
    respuesta: lista('Transportadora', TransportadoraSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/transportadoras',
    etiqueta: 'Maestros',
    resumen: 'Crear transportadora',
    guard: 'catalogos C',
    body: CrearTransportadoraSchema,
    respuesta: una('Transportadora', TransportadoraSchema, 201),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/transportadoras/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar transportadora',
    guard: 'catalogos U',
    body: ActualizarTransportadoraSchema,
    respuesta: una('Transportadora', TransportadoraSchema),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/transportadoras/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica',
    guard: 'catalogos D',
    respuesta: una('Transportadora', TransportadoraSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/tarifas',
    etiqueta: 'Maestros',
    resumen: 'Tarifas con vigencia',
    guard: 'tarifas R (finance, ops, superadmin)',
    query: FiltroTarifasSchema,
    respuesta: libre(
      'Tarifa',
      'Tarifa `{ id, clienteId, destinoId, claseVehiculo, modalidad, valor, vigenteDesde, vigenteHasta }`',
      true,
    ),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/tarifas',
    etiqueta: 'Maestros',
    resumen: 'Crear tarifa',
    guard: 'tarifas C (finance)',
    body: CrearTarifaSchema,
    respuesta: libre('Tarifa', 'Tarifa creada (201)'),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/tarifas/:id',
    etiqueta: 'Maestros',
    resumen: 'Actualizar tarifa',
    guard: 'tarifas U',
    body: ActualizarTarifaSchema,
    respuesta: libre('Tarifa', 'Tarifa'),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/tarifas/:id',
    etiqueta: 'Maestros',
    resumen: 'Baja lógica',
    guard: 'tarifas D',
    respuesta: libre('Tarifa', 'Tarifa'),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/tipos-documento',
    etiqueta: 'HSEQ',
    resumen: 'Tipos de documento (bloqueantes y días de alerta)',
    guard: 'documentos R (own)',
    respuesta: lista('TipoDocumento', TipoDocumentoSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/documentos',
    etiqueta: 'HSEQ',
    resumen: 'Documentos con semáforo calculado al leer',
    guard: 'documentos R (own)',
    query: FiltroDocumentosSchema,
    respuesta: lista('VistaDocumento', VistaDocumentoSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/documentos',
    etiqueta: 'HSEQ',
    resumen: 'Registrar documento (el archivo nunca va en la base)',
    guard: 'documentos C',
    body: CrearDocumentoSchema,
    respuesta: una('VistaDocumento', VistaDocumentoSchema, 201),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/documentos/:id',
    etiqueta: 'HSEQ',
    resumen: 'Renovar o corregir documento',
    guard: 'documentos U',
    body: ActualizarDocumentoSchema,
    respuesta: una('VistaDocumento', VistaDocumentoSchema),
  },
  {
    metodo: 'delete',
    ruta: '/api/v1/documentos/:id',
    etiqueta: 'HSEQ',
    resumen: 'Baja lógica',
    guard: 'documentos D',
    respuesta: una('VistaDocumento', VistaDocumentoSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/documentos/alertas',
    etiqueta: 'HSEQ',
    resumen: 'Vencidos y por vencer, del más urgente al menos (member: solo sus placas)',
    guard: 'documentos R (own)',
    query: Dias,
    respuesta: lista('AlertaDocumento', AlertaDocumentoSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/documentos/:id/soporte',
    etiqueta: 'HSEQ',
    resumen:
      'Pedir dónde subir el soporte (URL prefirmada de S3 o esta API); PDF, JPG o PNG hasta 10 MB',
    guard: 'documentos U',
    body: SolicitarSoporteSchema,
    respuesta: una('UrlSubida', UrlSubidaSchema),
  },
  {
    metodo: 'put',
    ruta: '/api/v1/soportes/*',
    etiqueta: 'HSEQ',
    resumen: 'Subida de bytes al almacén local (con S3 el navegador sube directo al bucket)',
    guard: 'documentos U',
    respuesta: una('SoporteGuardado', z.object({ clave: z.string(), tamano: z.number() }), 201),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/documentos/:id/soporte/confirmar',
    etiqueta: 'HSEQ',
    resumen:
      'Confirmar la subida: verifica el objeto y guarda la referencia en `archivoUrl` (auditado)',
    guard: 'documentos U',
    body: ConfirmarSoporteSchema,
    respuesta: una('VistaDocumento', VistaDocumentoSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/documentos/:id/soporte',
    etiqueta: 'HSEQ',
    resumen:
      'Descargar el soporte con el rol del actor (302 a URL prefirmada en S3, bytes en local); auditado',
    guard: 'documentos R (own)',
    respuesta: libre('Soporte', 'application/pdf o imagen (local), o 302 a la URL prefirmada (S3)'),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/jobs/recalcular-documentos',
    etiqueta: 'Jobs',
    resumen: 'Recalcular `documentos.estado` (auditado)',
    guard: 'documentos U',
    respuesta: una('Recalculo', z.object({ hoy: z.string(), recalculados: z.number() })),
  },

  // --- Operación (spec §8.4, §8.5) ------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/colas/:clase',
    etiqueta: 'Operación',
    resumen: 'Snapshot de la cola con elegibilidad por posición',
    guard: 'cola R (no own)',
    query: FiltroColaSchema,
    respuesta: una('VistaCola', VistaColaSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/colas/:clase/intervenciones',
    etiqueta: 'Operación',
    resumen: 'Overrides y resets de la clase (el veedor los ve)',
    guard: 'cola R',
    respuesta: lista('Intervencion', IntervencionSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/colas/:clase/override',
    etiqueta: 'Operación',
    resumen: 'Mover una placa a una posición con motivo (superadmin re-autenticado)',
    guard: 'cola U',
    reauth: true,
    body: OverrideColaSchema,
    respuesta: una('ColaIntervenida', ColaIntervenida),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/colas/:clase/reset',
    etiqueta: 'Operación',
    resumen: 'Reordenar la cola entera con motivo (superadmin re-autenticado)',
    guard: 'cola U',
    reauth: true,
    body: ResetColaSchema,
    respuesta: una('ColaIntervenida', ColaIntervenida),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/requerimientos',
    etiqueta: 'Operación',
    resumen: 'Requerimientos con cupos',
    guard: 'requerimientos R',
    query: FiltroRequerimientosSchema,
    respuesta: lista('VistaRequerimiento', VistaRequerimientoSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/requerimientos',
    etiqueta: 'Operación',
    resumen: 'Crear requerimiento',
    guard: 'requerimientos C',
    body: CrearRequerimientoSchema,
    respuesta: una('VistaRequerimiento', VistaRequerimientoSchema, 201),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/requerimientos/:id/ofertas',
    etiqueta: 'Operación',
    resumen: 'Ofrecer el cupo a la cabeza elegible (409 COLA_LOCKED si otro coordinador opera)',
    guard: 'ofertas C',
    respuesta: una('VistaOferta', VistaOfertaSchema, 201),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/ofertas',
    etiqueta: 'Operación',
    resumen: 'Ofertas',
    guard: 'ofertas R',
    query: FiltroOfertasSchema,
    respuesta: lista('VistaOferta', VistaOfertaSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/ofertas/:id/aceptar',
    etiqueta: 'Operación',
    resumen: 'Aceptar (member, solo la propia): genera el TR',
    guard: 'ofertas A (own)',
    respuesta: una('Aceptacion', z.object({ oferta: VistaOfertaSchema, tr: VistaTrSchema })),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/ofertas/:id/declinar',
    etiqueta: 'Operación',
    resumen: 'Declinar con motivo: aplica la política y reoferta al siguiente',
    guard: 'ofertas A (own)',
    body: DeclinarOfertaSchema,
    respuesta: una(
      'Declinacion',
      z.object({ oferta: VistaOfertaSchema, siguiente: VistaOfertaSchema.nullable() }),
    ),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/ofertas/:id/anular',
    etiqueta: 'Operación',
    resumen: 'Anular una oferta abierta (ops)',
    guard: 'ofertas A',
    body: MotivoSchema,
    respuesta: una('VistaOferta', VistaOfertaSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/trs',
    etiqueta: 'Operación',
    resumen: 'TR (member: los suyos)',
    guard: 'trs R (own)',
    query: FiltroTrsSchema,
    respuesta: lista('VistaTr', VistaTrSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/trs/:id',
    etiqueta: 'Operación',
    resumen: 'TR',
    guard: 'trs R (own)',
    respuesta: una('VistaTr', VistaTrSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/trs/:id/cancelar',
    etiqueta: 'Operación',
    resumen: 'Cancelar TR (la placa vuelve a la cabeza según parámetro)',
    guard: 'trs A',
    body: MotivoSchema,
    respuesta: una(
      'CancelacionTr',
      z.object({ tr: VistaTrSchema, siguiente: VistaOfertaSchema.nullable() }),
    ),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/trs/:id/no-tramitar',
    etiqueta: 'Operación',
    resumen: 'Marcar TR como no tramitado',
    guard: 'trs A',
    body: MotivoSchema,
    respuesta: una('VistaTr', VistaTrSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/me/cola',
    etiqueta: 'Mi turno',
    resumen: '"Tu posición: 3 de 12" por placa propia',
    guard: 'cola R (own)',
    respuesta: lista('MiPosicion', MiPosicionSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/me/ofertas',
    etiqueta: 'Mi turno',
    resumen: 'Ofertas de las placas propias',
    guard: 'ofertas R (own)',
    respuesta: lista('VistaOferta', VistaOfertaSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/me/trs',
    etiqueta: 'Mi turno',
    resumen: 'TR de las placas propias',
    guard: 'trs R (own)',
    respuesta: lista('VistaTr', VistaTrSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/me/extracto',
    etiqueta: 'Mi turno',
    resumen: 'Extracto habeas data (auditado)',
    guard: 'trs R (own), solo member',
    respuesta: libre(
      'Extracto',
      'Placas, TR, viajes, recaudos y textos de propósito/acceso/cancelación',
    ),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/jobs/expirar-ofertas',
    etiqueta: 'Jobs',
    resumen: 'Expirar ofertas vencidas',
    guard: 'cola U',
    respuesta: una('Expiracion', z.object({ expiradas: z.number() })),
  },

  // --- Viajes y recaudo (spec §6.5) -----------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/viajes',
    etiqueta: 'Finanzas',
    resumen: 'Viajes (member: los suyos; viewer enmascarado)',
    guard: 'viajes R (own)',
    query: FiltroViajesSchema,
    respuesta: lista('VistaViaje', VistaViajeSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/viajes/resumen',
    etiqueta: 'Finanzas',
    resumen: 'Resumen del mes: flete, recaudo, pagado, por cliente y por placa',
    guard: 'viajes R',
    query: ResumenMesSchema,
    respuesta: una('ResumenMes', VistaResumenMesSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/viajes/:id',
    etiqueta: 'Finanzas',
    resumen: 'Detalle con tarifas sugeridas y recaudo',
    guard: 'viajes R (own)',
    respuesta: una('DetalleViaje', DetalleViajeSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/recaudos',
    etiqueta: 'Finanzas',
    resumen: 'Recaudos',
    guard: 'recaudos R (own)',
    query: FiltroRecaudosSchema,
    respuesta: libre('VistaRecaudo', 'Recaudo con TR, placa, asociado y pagado', true),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/viajes',
    etiqueta: 'Finanzas',
    resumen: 'Crear el viaje de un TR (VIAJE_YA_EXISTE si ya tiene)',
    guard: 'viajes C',
    body: CrearViajeSchema,
    respuesta: una('DetalleViaje', DetalleViajeSchema, 201),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/viajes/:id',
    etiqueta: 'Finanzas',
    resumen: 'Actualizar viaje (no liquidado)',
    guard: 'viajes U',
    body: ActualizarViajeSchema,
    respuesta: una('DetalleViaje', DetalleViajeSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/viajes/:id/liquidar',
    etiqueta: 'Finanzas',
    resumen:
      'Liquidar: fija el recaudo con el porcentaje vigente (snapshot) y marca el TR cumplido',
    guard: 'recaudos C',
    body: LiquidarViajeSchema,
    respuesta: una('DetalleViaje', DetalleViajeSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/viajes/:id/anular',
    etiqueta: 'Finanzas',
    resumen: 'Anular viaje con motivo',
    guard: 'viajes D',
    body: AnularViajeSchema,
    respuesta: una('DetalleViaje', DetalleViajeSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/recaudos/:id/pagos',
    etiqueta: 'Finanzas',
    resumen: 'Registrar pago (parcial o total)',
    guard: 'recaudos U',
    body: RegistrarPagoSchema,
    respuesta: libre('VistaRecaudo', 'Recaudo actualizado'),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/export/viajes.csv',
    etiqueta: 'Finanzas',
    resumen: 'CSV del mes con marca de agua (viewer sin PII, member solo lo propio)',
    guard: 'export A (own)',
    query: Mes,
    respuesta: libre('Csv', 'text/csv con marca de agua en la primera línea'),
  },

  // --- Tablero (spec §9.2 Viewer) ---------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/tablero',
    etiqueta: 'Tablero',
    resumen: 'Tablero del mes: ofertas, TR, viajes, equidad por placa',
    guard: 'trs R',
    query: Mes,
    respuesta: una('Tablero', TableroSchema),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/tablero/snapshots',
    etiqueta: 'Tablero',
    resumen: 'Snapshots mensuales guardados',
    guard: 'trs R',
    query: MesOpcional,
    respuesta: lista('SnapshotMes', SnapshotMesSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/jobs/snapshot-metricas',
    etiqueta: 'Jobs',
    resumen: 'Snapshot de equidad del mes (por defecto el anterior); auditado',
    guard: 'cola U',
    body: MesCuerpo,
    respuesta: una('SnapshotMes', SnapshotMesSchema),
  },

  // --- IAM (spec §8.2) ----------------------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/usuarios',
    etiqueta: 'Usuarios',
    resumen: 'Usuarios',
    guard: 'usuarios R',
    respuesta: { ...Usuario, lista: true },
  },
  {
    metodo: 'get',
    ruta: '/api/v1/usuarios/:id',
    etiqueta: 'Usuarios',
    resumen: 'Usuario',
    guard: 'usuarios R',
    respuesta: Usuario,
  },
  {
    metodo: 'post',
    ruta: '/api/v1/usuarios',
    etiqueta: 'Usuarios',
    resumen: 'Crear usuario (member sin contraseña; correo único)',
    guard: 'usuarios C (superadmin)',
    body: CrearUsuarioSchema,
    respuesta: { ...Usuario, status: 201 },
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/usuarios/:id',
    etiqueta: 'Usuarios',
    resumen: 'Actualizar (desactivar revoca sesiones)',
    guard: 'usuarios U (superadmin)',
    body: ActualizarUsuarioSchema,
    respuesta: Usuario,
  },
  {
    metodo: 'post',
    ruta: '/api/v1/usuarios/:id/roles',
    etiqueta: 'Usuarios',
    resumen: 'Cambiar rol (revoca sesiones; limpia placas al salir de member)',
    guard: 'usuarios U (superadmin)',
    body: CambiarRolSchema,
    respuesta: Usuario,
  },
  {
    metodo: 'post',
    ruta: '/api/v1/usuarios/:id/vehiculos',
    etiqueta: 'Usuarios',
    resumen: 'Placas del asociado (scope member)',
    guard: 'usuarios U (superadmin)',
    body: AsignarVehiculosSchema,
    respuesta: Usuario,
  },

  // --- Notificaciones (spec §11) -------------------------------------------------------------------------
  {
    metodo: 'get',
    ruta: '/api/v1/me/notificaciones',
    etiqueta: 'Notificaciones',
    resumen: 'Bandeja del usuario, más reciente primero',
    guard: 'token (propias)',
    query: FiltroNotificacionesSchema,
    respuesta: lista('Notificacion', NotificacionSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/me/notificaciones/:id/leer',
    etiqueta: 'Notificaciones',
    resumen: 'Marcar leída (idempotente; 404 si no es suya)',
    guard: 'token (propias)',
    respuesta: una('Ok', Ok),
  },
  {
    metodo: 'get',
    ruta: '/api/v1/me/preferencias',
    etiqueta: 'Notificaciones',
    resumen: 'Canales opt-in del usuario',
    guard: 'token (propias)',
    respuesta: una('PreferenciasNotificacion', PreferenciasNotificacionSchema),
  },
  {
    metodo: 'patch',
    ruta: '/api/v1/me/preferencias',
    etiqueta: 'Notificaciones',
    resumen: 'Cambiar canales (auditado sin el celular)',
    guard: 'token (propias)',
    body: PreferenciasNotificacionSchema,
    respuesta: una('PreferenciasNotificacion', PreferenciasNotificacionSchema),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/jobs/notificar',
    etiqueta: 'Jobs',
    resumen: 'Una pasada del worker de avisos',
    guard: 'cola U',
    respuesta: una(
      'ResultadoWorker',
      z.object({ avisos: z.number(), entregas: z.number(), fallos: z.number() }),
    ),
  },
  {
    metodo: 'post',
    ruta: '/api/v1/jobs/avisos',
    etiqueta: 'Jobs',
    resumen: 'Avisos por tiempo: oferta por expirar, documento por vencer, digest de recaudo',
    guard: 'cola U',
    respuesta: una(
      'ResumenAvisos',
      z.object({ porExpirar: z.number(), documentos: z.number(), recaudos: z.boolean() }),
    ),
  },
];
