// Códigos de error estables (spec §8.6, RULE-020). El frontend traduce; el código no cambia.

export const CODIGOS_ERROR = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  CHALLENGE_INVALIDO: 401,
  CODIGO_INVALIDO: 401,
  FORBIDDEN: 403,
  FORBIDDEN_OWN_SCOPE: 403,
  REAUTH_REQUERIDA: 403,
  NOT_FOUND: 404,
  TOTP_NO_ENROLADO: 409,
  COLA_LOCKED: 409,
  /** Acta de turno (brief §5): la cola cambió entre la vista previa y el clic; sin efectos. */
  CANDIDATO_CAMBIO: 409,
  EMAIL_EN_USO: 409,
  PLACA_EN_USO: 409,
  DOCUMENTO_EN_USO: 409,
  CATALOGO_EN_USO: 409,
  TARIFA_DUPLICADA: 409,
  VEHICULO_CON_HISTORIA: 409,
  TR_DUPLICADO: 409,
  OFERTA_NO_ABIERTA: 409,
  REQUERIMIENTO_CERRADO: 409,
  REQUERIMIENTO_SIN_CUPOS: 409,
  TR_NO_CANCELABLE: 409,
  VERSION_CONFLICT: 409,
  VIAJE_YA_EXISTE: 409,
  VIAJE_LIQUIDADO: 409,
  VIAJE_ANULADO: 409,
  RECAUDO_CERRADO: 409,
  COLA_VACIA: 422,
  VEHICULO_NO_HABILITADO: 422,
  VEHICULO_NO_ACTIVO: 422,
  DOCUMENTO_VENCIDO: 422,
  BLOQUEO_TEMPORAL: 422,
  OFERTA_ABIERTA_PREVIA: 422,
  TR_ACTIVO: 422,
  PENALIZACION_PENDIENTE: 422,
  OFERTA_EXPIRADA: 422,
  MOTIVO_REQUERIDO: 422,
  TR_NO_VIAJABLE: 422,
  VIAJE_NO_LIQUIDABLE: 422,
  PAGO_INVALIDO: 422,
  RATE_LIMITED: 429,
  DEMASIADOS_INTENTOS: 429,
  INVARIANTE_COLA: 500,
  INTERNAL: 500,
} as const;

export type CodigoError = keyof typeof CODIGOS_ERROR;

export function httpStatusDe(codigo: CodigoError): number {
  return CODIGOS_ERROR[codigo];
}

export interface ErrorApi {
  code: CodigoError;
  message: string;
  details?: Record<string, unknown>;
}
