// Tipos de las respuestas de la API, derivados del contrato compartido (TASK-0033):
// packages/shared/src/vistas.ts los define en Zod, la API los valida en apps/api/src/openapi.test.ts
// y los publica en GET /api/v1/openapi.json (docs/openapi.json). Aquí solo se reexportan con los
// nombres que usan las páginas; no hay nada que mantener a mano.

export type {
  AlertaDocumento,
  Cliente,
  DetalleViaje,
  Elegibilidad,
  EventoAuditoria,
  Intervencion,
  MetricaPlaca,
  MiPosicion,
  MotivoDeclinacion,
  Notificacion,
  PreferenciasNotificacion,
  RespuestaLogin,
  ResumenMes,
  SemaforoPlaca,
  Sesion,
  Tablero,
  TarifaSugerida,
  TipoDocumento,
  Transportadora,
  UsuarioSesion,
  VistaAsociado,
  VistaCola,
  VistaConductorFicha,
  VistaDocumento,
  VistaFicha,
  VistaHabilitacion,
  VistaOferta,
  VistaPosicion,
  VistaRecaudo,
  VistaRequerimiento,
  VistaTr,
  VistaVehiculo,
  VistaVehiculoRegistro,
  VistaViaje,
} from '@asotracmet/shared';
